### ISSUE TITLE
Default nbt-type for BrewTime attribute of brewing stands is incorrect

### ISSUE THREAD

**Issue by zheskett** [SPGoding/datapack-language-server#545] opened 2020-06-29 17:01 UTC
When using `brewing_stand{BrewTime: 0s}`, the default tag for BrewTime is int, however, the game defaults to short, so a warning shows up for this line.

**Comment by SPGoding** [comment] 2020-06-30 20:03
Duplicate of Yurihaia/mc-nbtdoc#10

**Closed by SPGoding** 2020-06-30 20:03 UTC
Labels: 🔥 duplicate, 🔷 nbt
