### ISSUE TITLE
Unknown keys and no NBT support for trapped chest

### ISSUE THREAD

**Issue by misode** [SPGoding/datapack-language-server#449] opened 2020-05-03 13:07 UTC
No suggestions are given and warnings show for each key.
![image](https://user-images.githubusercontent.com/17352009/80915028-afd31300-8d4f-11ea-95a3-50dcc16d03df.png)

**Comment by SPGoding** [comment] 2020-05-03 20:19
Duplicate of Yurihaia/mc-nbtdoc#6

**Closed by SPGoding** 2020-05-03 20:19 UTC
