### ISSUE TITLE
Loot table function `enchant_randomly.enchantments` property is not optional 

### ISSUE THREAD

**Issue by SirWindfield** [SPGoding/datapack-language-server#727] opened 2020-10-25 16:27 UTC
Per wiki, the field is actually optional and defaults to all enchantments if not set. However, current linting does throw an error if the field is not specified (expected an array).

**Comment by ChenCMD** [comment] 2020-10-26 04:29
Duplicate of misode/minecraft-schemas#11

**Closed by ChenCMD** 2020-10-26 04:29 UTC
Labels: 🐛 bug, 🔥 forwarded, 🔷 json
