### ISSUE TITLE
Scoped #define tag

### ISSUE THREAD

**Issue by oOBoomberOo** [SPGoding/datapack-language-server#490] opened 2020-06-16 15:10 UTC
When writing a datapack, I tend to use a lot of temporary score inside a function which would never be used outside of it ever again. Pilling up those scores into the global list doesn't seem ideal since the score shouldn't be used outside of this function.
```mcfunction
#define score_holder pos.x
#define score_holder pos.y
#define score_holder pos.z

# Do some math with those scores...
```

So I would like a new #define syntax that will only suggest them within the function itself
```mcfunction
#define_scope score_holder pos.x
#define_scope score_holder pos.y
#define_scope score_holder pos.z
```
Having a scoped suggestion also helps to remind you which score isn't supposed to be used outside of a function.

Note: You didn't enable issues labeling for a normal user so you have to label this one yourself.

**Comment by SPGoding** [comment] 2020-06-16 15:44
Actually this is something I always want to do, so this is a duplicate of #319

Thanks for report anyways!

**Closed by SPGoding** 2020-06-16 15:44 UTC
Labels: 🔥 duplicate
