### ISSUE TITLE
missing NBT tag for Player

### ISSUE THREAD

**Issue by end-user** [SPGoding/datapack-language-server#722] opened 2020-10-14 03:10 UTC
The Player has a `previousPlayerGameType` NBT introduced in 1.16.  I don't know where in the code these are defined or I'd submit a PR.

**Comment by MulverineX** [comment] 2020-10-14 03:11
@end-user https://github.com/Yurihaia/mc-nbtdoc

**Comment by SPGoding** [comment] 2020-10-14 03:11
Those NBT data are stored in https://github.com/Yurihaia/mc-nbtdoc

**Comment by MulverineX** [comment] 2020-10-14 03:11
https://github.com/Yurihaia/mc-nbtdoc/blob/master/minecraft/entity/mob/player.nbtdoc

**Comment by SPGoding** [comment] 2020-10-14 04:40
Duplicate of Yurihaia/mc-nbtdoc#25

**Closed** 2020-10-14 04:40 UTC
Labels: 🔥 forwarded, 🔷 nbt
