### ISSUE TITLE
Error!

### ISSUE THREAD

**Issue by barraIhsan** [SPGoding/datapack-language-server#701] opened 2020-09-26 06:42 UTC
[onInitialize] CacheVersion = 11
[onInitialize] ReleaseNotesVersion = 3.0.0
[onInitialize] globalStoragePath = c:\Users\barra\AppData\Roaming\Code\User\globalStorage\spgoding.datapack-language-server
[onInitialize] cachePath = c:\Users\barra\AppData\Roaming\Code\User\workspaceStorage\dceea1750c2d500ed8cb8d1ed003d466\SPGoding.datapack-language-server\cache.json
[onInitialize] pluginsPath = c:\Users\barra\AppData\Roaming\Code\User\globalStorage\spgoding.datapack-language-server\plugins
[PluginLoader] Registered “spgoding:doc_comment”
[PluginLoader] Registered “spgoding:mcfunction”
[PluginLoader] 2 ms
[LatestVersions] Fetching the latest versions...
[LatestVersions] versionInformation = {"latestRelease":"1.16.3","latestSnapshot":"1.16.3","processedVersions":["1.16.3","1.16.3-rc1","1.16.2","1.16.2-rc2","1.16.2-rc1","1.16.2-pre3","1.16.2-pre2","1.16.2-pre1"]}
[I18N] Default: “en”.
[VanillaData: BlockDefinition for 1.16.3] Loading from local file ${globalStoragePath}\1.16.3\BlockDefinition.json...
[updateRoots] Data pack 1 = “file:///c%3A/Users/barra/AppData/Roaming/.minecraft/saves/Ender%20Dragon%20Practice/datapacks/Ender%20Dragon%20Practice/”
[VanillaData: BlockDefinition for 1.16.3] Loaded from local file.
[VanillaData: NamespaceSummary for 1.16.3] Loading from local file ${globalStoragePath}\1.16.3\NamespaceSummary.json...
[VanillaData: NamespaceSummary for 1.16.3] Loaded from local file.
[VanillaData: NamespaceSummary for 1.16.3] Merged MyNamespaceSummary.json in.
[VanillaData: Nbtdoc for 1.16.3] Loading from local file ${globalStoragePath}\1.16.3\Nbtdoc.json...
[VanillaData: Nbtdoc for 1.16.3] Loaded from local file.
[VanillaData: Registry for 1.16.3] Loading from local file ${globalStoragePath}\1.16.3\Registry.json...
[VanillaData: Registry for 1.16.3] Loaded from local file.
(node:21532) UnhandledPromiseRejectionWarning: TypeError: this.activeCase is not a function
    at Object.navigate (c:\Users\barra\.vscode\extensions\spgoding.datapack-language-server-3.0.4\dist\server.js:1529:31)
    at Object.navigate (c:\Users\barra\.vscode\extensions\spgoding.datapack-language-server-3.0.4\dist\server.js:1359:55)
    at Object.navigate (c:\Users\barra\.vscode\extensions\spgoding.datapack-language-server-3.0.4\dist\server.js:899:29)
    at Object.navigate (c:\Users\barra\.vscode\extensions\spgoding.datapack-language-server-3.0.4\dist\server.js:1359:55)
    at Object.navigate (c:\Users\barra\.vscode\extensions\spgoding.datapack-language-server-3.0.4\dist\server.js:1529:114)
    at c:\Users\barra\.vscode\extensions\spgoding.datapack-language-server-3.0.4\dist\server.js:25941:43
    at Function.walkAstNode (c:\Users\barra\.vscode\extensions\spgoding.datapack-language-server-3.0.4\dist\server.js:26133:9)
    at Function.walkAstNode (c:\Users\barra\.vscode\extensions\spgoding.datapack-language-server-3.0.4\dist\server.js:26145:22)
    at Function.validate (c:\Users\barra\.vscode\extensions\spgoding.datapack-language-server-3.0.4\dist\server.js:25940:14)
    at Object.parseJsonNode (c:\Users\barra\.vscode\extensions\spgoding.datapack-language-server-3.0.4\dist\server.js:23080:41)
(node:21532) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:21532) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[updateCacheFile] [1] 129 ms
[updateCacheFile] [2] 21 ms
[updateCacheFile] [T] 150 ms
[Error - 1:39:31 PM] Request textDocument/colorPresentation failed.
  Message: Request textDocument/documentColor failed with message: this.activeCase is not a function
  Code: -32603 
[Error - 1:39:31 PM] Request textDocument/documentLink failed.
  Message: Request textDocument/documentLink failed with message: this.activeCase is not a function
  Code: -32603 
[Error - 1:39:31 PM] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: this.activeCase is not a function
  Code: -32603 
[Error - 1:39:31 PM] Request textDocument/foldingRange failed.
  Message: Request textDocument/foldingRange failed with message: this.activeCase is not a function
  Code: -32603 
[Error - 1:39:31 PM] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: this.activeCase is not a function
  Code: -32603

**Comment by SPGoding** [comment] 2020-09-26 21:00
Duplicate of #700

**Closed by SPGoding** 2020-09-26 21:00 UTC
