### ISSUE TITLE
No autocomplete NBT Tags in data modify append value

### ISSUE THREAD

**Issue by barraIhsan** [SPGoding/datapack-language-server#772] opened 2020-11-28 13:08 UTC
Try `data modify entity @s CustomPotionEffects append value {}` Then there is no autocomplete
![image](https://user-images.githubusercontent.com/57800056/100516316-9eeb6280-31b5-11eb-9b6a-d733b4640d1f.png)

**Comment by SPGoding** [comment] 2020-11-28 19:55
Duplicate of #400.

**Comment by SPGoding** [comment] 2020-11-28 19:55
Duplicate of #400

**Comment by SPGoding** [comment] 2020-11-28 19:56
Duplicate of #400

**Closed** 2020-11-28 19:56 UTC
Labels: 🐛 bug, 🔥 forwarded, 🔷 nbt
