### ISSUE TITLE
Intellisense stops working after a while.

### ISSUE THREAD

**Issue by dragon3025** [SPGoding/datapack-language-server#187] opened 2019-11-27 03:43 UTC

**Comment by SPGoding** [comment] 2019-11-27 15:14
What commands have you used? 

Is there any text components in your commands? If so, there are some bugs of parsing text components which will likely be fixed in the next version. Sorry for the inconvenience!

**Comment by dragon3025** [comment] 2019-11-27 19:00
I used tellraw a lot in one of tabs I had open, an mcfunction called "xp_storage". It was preventing intellisense in all tabs, even if I reload visual studio code or if I just close "xp_storage". If I close "xp_storage" then reload, then it starts working again.

**Comment by SPGoding** [comment] 2019-11-27 20:14
Then this is caused by text components. This is technically a duplicate of #176, which have already been fixed and will be released in the next version (likely in a few days). Thanks for reporting and sorry for the inconvenience!

**Closed by SPGoding** 2019-11-27 20:14 UTC
Labels: :bug: bug, :zap: performance
