### ISSUE TITLE
There is a function that DHP does not work.

### ISSUE THREAD

**Issue by ChenCMD** [SPGoding/datapack-language-server#514] opened 2020-06-25 07:14 UTC
![image](https://user-images.githubusercontent.com/46134240/85673417-d33a8e80-b6fe-11ea-8537-91ccc72f476b.png)

**Comment by SPGoding** [comment] 2020-06-25 17:25
:thinking: Does reopening that file fix this issue?

**Comment by ChenCMD** [comment] 2020-06-25 18:06
No, I could not solve it except by lowering the version of DHP.

**Comment by SPGoding** [comment] 2020-06-26 05:19
![image](https://user-images.githubusercontent.com/15277496/85823306-af00a100-b742-11ea-8655-7cf8c777c15d.png)

I tried exactly the same path and file names, but still couldn't reproduce this

**Comment by ChenCMD** [comment] 2020-06-26 05:21
Hmm, it's strange. I will check a little more here.

**Comment by ChenCMD** [comment] 2020-06-26 05:34
When I checked the output, the same TypeError as #512 was output in the file where DHP did not work.
I will attach the output.
![image](https://user-images.githubusercontent.com/46134240/85824196-2c1b2d00-b7ba-11ea-91d2-87f0aa27341a.png)

**Comment by SPGoding** [comment] 2020-06-26 06:24
Duplicate of #512 then; sorry for any inconvenience!

A new version **2.1.1** has been released which should have fixed this bug.

**Closed by SPGoding** 2020-06-26 06:24 UTC
Labels: 🔥 duplicate
