### ISSUE TITLE
Expected ‘belowName’, ‘list’ or ‘sidebar’ but got ‘belowname’.

### ISSUE THREAD

**Issue by ChenCMD** [SPGoding/datapack-language-server#240] opened 2020-01-04 12:32 UTC
![image](https://user-images.githubusercontent.com/46134240/71765545-99e84980-2f39-11ea-8c73-2922fb681896.png)

**Comment by SPGoding** [comment] 2020-01-04 17:51
I thought it was case-sensitive. I was wrong again.

This will be fixed in a longer time than usual 'cause I am refactoring something.

Anyway, writing `belowName` is better.
![image](https://user-images.githubusercontent.com/15277496/71769544-73e68900-2ee8-11ea-8a01-5f0afb3a3eae.png)

**Comment by SPGoding** [comment] 2020-01-05 06:32
Well, I changed my mind. Won't fix unless [MC-169464](https://bugs.mojang.com/browse/MC-169464) is marked as Working As Intended by Mojang.

**Closed by SPGoding** 2020-01-05 06:32 UTC
Labels: :bug: bug
