### ISSUE TITLE
#define custom NBT tag paths

### ISSUE THREAD

**Issue by PsiGreenEx** [SPGoding/datapack-language-server#546] opened 2020-07-01 22:48 UTC
My ideas for more define options are:
`storage_path`: Define custom NBT tag paths for when you are using data storage.
~~`dimension` and `dimension_type`: Define custom dimensions and dimension types.~~

Edit: Second one was already suggested, sorry.

**Comment by SPGoding** [comment] 2020-07-02 03:51
> ~~`dimension` and `dimension_type`: Define custom dimensions and dimension types.~~
Thanks for reminding, I almost forgot that! Now tracked in #547.

The custom NBT path definition would be really nice to have, however it requires some work to compile the NBT paths to the format the language server uses internally, so don't expect it come true soon ;D

**Comment by SPGoding** [comment] 2020-08-15 23:18
Duplicate of #657

**Closed** 2020-08-15 23:18 UTC
Labels: 🔥 duplicate
