### ISSUE TITLE
DealtDamage NBT tag on Trident is not recognised

### ISSUE THREAD

**Issue by Up-Level** [SPGoding/datapack-language-server#707] opened 2020-10-07 16:47 UTC
DealtDamage is an NBT tag for the trident but it gives the warning " Unknown key “DealtDamage”. "
![image](https://user-images.githubusercontent.com/24874283/95361635-e3006c00-08c4-11eb-97a8-eb6164965a15.png)

**Comment by SPGoding** [comment] 2020-10-07 16:53
Duplicate of mc-nbtdoc#24

**Comment by SPGoding** [comment] 2020-10-07 16:54
Duplicate of Yurihaia/mc-nbtdoc#24

**Closed** 2020-10-07 16:54 UTC
Labels: 🐛 bug, 🔥 duplicate, 🔷 nbt
