### ISSUE TITLE
No autocomplete NBT Tag in data modify

### ISSUE THREAD

**Issue by barraIhsan** [SPGoding/datapack-language-server#766] opened 2020-11-24 03:29 UTC
Try `data modify block ~ ~ ~ Items insert 0 value {}` then there is no autocomplete
![image](https://user-images.githubusercontent.com/57800056/100043353-dd90be00-2e3f-11eb-9d1e-8ae85417cb48.png)

**Comment by SPGoding** [comment] 2020-11-28 19:57
Duplicate of #400

**Closed** 2020-11-28 19:57 UTC
Labels: 🐛 bug, 🔥 forwarded, 🔷 nbt
