### ISSUE TITLE
Removing the ending quote of a json string and asking for completion spams the log with errors

### ISSUE THREAD

**Issue by misode** [SPGoding/datapack-language-server#713] opened 2020-10-10 00:53 UTC
![image](https://user-images.githubusercontent.com/17352009/95641600-adfe4000-0aa3-11eb-853f-4558fc6d4eb2.png)

**Comment by SPGoding** [comment] 2020-10-10 01:37
Duplicate of #671

**Closed** 2020-10-10 01:37 UTC
Labels: 🔥 forwarded
