### ISSUE TITLE
Dimension Tag in 1.15 vs 1.16

### ISSUE THREAD

**Issue by DuncanRL** [SPGoding/datapack-language-server#583] opened 2020-07-13 02:04 UTC
Datapack Helper Plus states that the Dimension NBT tag is an integer, which is correct for 1.15.2 and below, however, in 1.16, it is a namespaced ID string.

A command to reproduce:
`execute if entity @e[nbt={Dimension:"minecraft:overworld"}] run say Someone is in the overworld`

From the [1.16 update page](https://minecraft.gamepedia.com/Java_Edition_1.16#General_2): The `Dimension` NBT tag is now a namespaced ID string instead of a number, which is used in player.dat.

**Comment by SPGoding** [comment] 2020-07-13 03:06
Duplicate of Yurihaia/mc-nbtdoc#13

**Closed by SPGoding** 2020-07-13 03:06 UTC
Labels: 🐛 bug, 🔥 duplicate, 🔷 nbt
